// Drizzle table definitions live here (or are re-exported from here).
// auth-schema.ts is generated by `npm run auth:generate` — regenerate it rather than editing by hand.
export * from "./auth-schema";
export * from "./catalog-schema";
